// <auto-generated />
using System;
using BookShelf.Repository.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShelf.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookShelf.Core.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("406578b9-d472-40a3-893f-3cf067a8d576"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1907, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(1948, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sabahattin",
                            IsDeleted = false,
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = new Guid("5123cef2-1f48-4a06-9d80-2190835194a3"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joanne",
                            IsDeleted = false,
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = new Guid("1c6447ef-86a2-49e2-b092-cd605942e899"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1889, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(1956, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Reşat Nuri",
                            IsDeleted = false,
                            LastName = "Güntekin"
                        },
                        new
                        {
                            Id = new Guid("5c8c320b-f8aa-4fa9-b776-2dda1c7f2fab"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1952, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert Cecil",
                            IsDeleted = false,
                            LastName = "Martin"
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            AuthorId = new Guid("1c6447ef-86a2-49e2-b092-cd605942e899"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Çalıkuşu"
                        },
                        new
                        {
                            Id = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            AuthorId = new Guid("406578b9-d472-40a3-893f-3cf067a8d576"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Kuyucaklı Yusuf"
                        },
                        new
                        {
                            Id = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            AuthorId = new Guid("406578b9-d472-40a3-893f-3cf067a8d576"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Acımak"
                        },
                        new
                        {
                            Id = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            AuthorId = new Guid("5123cef2-1f48-4a06-9d80-2190835194a3"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Harry Potter Sırlar Odası"
                        },
                        new
                        {
                            Id = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            AuthorId = new Guid("5c8c320b-f8aa-4fa9-b776-2dda1c7f2fab"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Clean Code"
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a417840-eea5-489e-9b23-ee8a89377a83"),
                            BookId = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("91ed6e02-013c-46fe-b683-1338f2eb2b39"),
                            BookId = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            CategoryId = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("740e9092-8bee-4f65-82bc-72134ebc0aa0"),
                            BookId = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("cea1cc07-3059-4d1e-a1c3-cf6233d45dc2"),
                            BookId = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            CategoryId = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("a83907ab-5deb-4bab-8a37-a90c43b1ff53"),
                            BookId = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("bba9cce3-412a-4e51-ae65-1190955e9470"),
                            BookId = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            CategoryId = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("647caf0e-0b5f-42a5-ae41-11f6c47ad5d2"),
                            BookId = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("7138ddf9-50b5-4b58-87e7-2a91e39c3b84"),
                            BookId = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            CategoryId = (short)3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0804be5c-55ba-47a3-a114-859cb9839006"),
                            BookId = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            CategoryId = (short)4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("957c82e5-51e6-413d-8e41-150fe97839d2"),
                            BookId = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            CategoryId = (short)5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short>("Pages")
                        .HasColumnType("smallint");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f2fca36-4141-413b-aeee-a568446d671f"),
                            BookId = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9785486037986",
                            IsDeleted = false,
                            Pages = (short)409,
                            ReleaseYear = (short)1922
                        },
                        new
                        {
                            Id = new Guid("20012823-a83c-4836-96d3-5cd5b36100e3"),
                            BookId = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9786051215877",
                            IsDeleted = false,
                            Pages = (short)222,
                            ReleaseYear = (short)1937
                        },
                        new
                        {
                            Id = new Guid("14a41b6b-1087-4ede-88e0-5cfabafb27bd"),
                            BookId = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9789751026569",
                            IsDeleted = false,
                            Pages = (short)160,
                            ReleaseYear = (short)1928
                        },
                        new
                        {
                            Id = new Guid("bff5e8e6-3fa2-4ca6-91d1-f201f7ea3186"),
                            BookId = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            Country = "İngiltere",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9781408855669",
                            IsDeleted = false,
                            Pages = (short)314,
                            ReleaseYear = (short)1998
                        },
                        new
                        {
                            Id = new Guid("3dead5ee-44d5-4a08-82a2-8685942fc193"),
                            BookId = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            Country = "Amerika",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "978-0132350884",
                            IsDeleted = false,
                            Pages = (short)464,
                            ReleaseYear = (short)2008
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.Category", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Edebiyat"
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Fantastik"
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Akademik"
                        },
                        new
                        {
                            Id = (short)5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Yazılım"
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.Book", b =>
                {
                    b.HasOne("BookShelf.Core.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookCategory", b =>
                {
                    b.HasOne("BookShelf.Core.Models.Book", "Book")
                        .WithMany("BookCategory")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookShelf.Core.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookDetail", b =>
                {
                    b.HasOne("BookShelf.Core.Models.Book", "Book")
                        .WithOne("BookDetail")
                        .HasForeignKey("BookShelf.Core.Models.BookDetail", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookShelf.Core.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookShelf.Core.Models.Book", b =>
                {
                    b.Navigation("BookCategory");

                    b.Navigation("BookDetail");
                });

            modelBuilder.Entity("BookShelf.Core.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
