// <auto-generated />
using System;
using BookShelf.Repository.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShelf.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookShelf.Core.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("406578b9-d472-40a3-893f-3cf067a8d576"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1907, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(1948, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sabahattin",
                            IsDeleted = false,
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = new Guid("5123cef2-1f48-4a06-9d80-2190835194a3"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joanne",
                            IsDeleted = false,
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = new Guid("1c6447ef-86a2-49e2-b092-cd605942e899"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1889, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(1956, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Reşat Nuri",
                            IsDeleted = false,
                            LastName = "Güntekin"
                        },
                        new
                        {
                            Id = new Guid("5c8c320b-f8aa-4fa9-b776-2dda1c7f2fab"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1952, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert Cecil",
                            IsDeleted = false,
                            LastName = "Martin"
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            AuthorId = new Guid("1c6447ef-86a2-49e2-b092-cd605942e899"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Çalıkuşu"
                        },
                        new
                        {
                            Id = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            AuthorId = new Guid("406578b9-d472-40a3-893f-3cf067a8d576"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Kuyucaklı Yusuf"
                        },
                        new
                        {
                            Id = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            AuthorId = new Guid("406578b9-d472-40a3-893f-3cf067a8d576"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Acımak"
                        },
                        new
                        {
                            Id = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            AuthorId = new Guid("5123cef2-1f48-4a06-9d80-2190835194a3"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Harry Potter Sırlar Odası"
                        },
                        new
                        {
                            Id = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            AuthorId = new Guid("5c8c320b-f8aa-4fa9-b776-2dda1c7f2fab"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Clean Code"
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e20d4216-fb30-4069-892e-edb2bcf62a4d"),
                            BookId = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8ad54afa-1ab7-4701-b39a-e3d6e8a029fe"),
                            BookId = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            CategoryId = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d82f02f0-f892-404b-9e26-1a871d180477"),
                            BookId = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("5fdb7cc9-ecc1-4b95-8a6e-f268915ebe03"),
                            BookId = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            CategoryId = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("20baeb6b-a8b1-4ae8-81cb-d2c74adc2de5"),
                            BookId = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("2b07aec1-1ed5-4352-af88-7aee940ab16d"),
                            BookId = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            CategoryId = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("01fa3733-6bdc-4c48-a282-ce5149a15a95"),
                            BookId = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            CategoryId = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("eae5138d-8368-42a9-8afe-9ebf67780ee8"),
                            BookId = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            CategoryId = (short)3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0dd5dc24-fdd3-40db-a54c-93fae3b6e263"),
                            BookId = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            CategoryId = (short)4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("eca7b9a6-f11c-4640-bfcd-8cef21a4853a"),
                            BookId = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            CategoryId = (short)5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("Pages")
                        .HasColumnType("smallint");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d184446-424e-40a6-9413-b53e6fcb0385"),
                            BookId = new Guid("8f5ff94d-95e5-403b-87a1-772d4f92d389"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9785486037986",
                            IsDeleted = false,
                            Pages = (short)409,
                            ReleaseYear = (short)1922
                        },
                        new
                        {
                            Id = new Guid("7b80d2e0-245a-49e6-a601-cad3abba5487"),
                            BookId = new Guid("2f01b12b-e101-4bef-ac48-6477cd922512"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9786051215877",
                            IsDeleted = false,
                            Pages = (short)222,
                            ReleaseYear = (short)1937
                        },
                        new
                        {
                            Id = new Guid("cc5930ad-834d-4863-9cdf-5a4ac602059a"),
                            BookId = new Guid("7740c465-3549-40e8-8a34-1ede6b02bfff"),
                            Country = "Türkiye",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9789751026569",
                            IsDeleted = false,
                            Pages = (short)160,
                            ReleaseYear = (short)1928
                        },
                        new
                        {
                            Id = new Guid("a412ac71-a741-4ce9-9150-b95bdb12e82b"),
                            BookId = new Guid("160fbeaf-7685-41be-b0ad-151cbd357909"),
                            Country = "İngiltere",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9781408855669",
                            IsDeleted = false,
                            Pages = (short)314,
                            ReleaseYear = (short)1998
                        },
                        new
                        {
                            Id = new Guid("dcf930d9-465a-46ad-b068-8a8b22a887c7"),
                            BookId = new Guid("ef074b57-3699-47d6-a22c-7c6e7725a2b3"),
                            Country = "Amerika",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "978-0132350884",
                            IsDeleted = false,
                            Pages = (short)464,
                            ReleaseYear = (short)2008
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.Category", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Edebiyat"
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Fantastik"
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Akademik"
                        },
                        new
                        {
                            Id = (short)5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Yazılım"
                        });
                });

            modelBuilder.Entity("BookShelf.Core.Models.Book", b =>
                {
                    b.HasOne("BookShelf.Core.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookCategory", b =>
                {
                    b.HasOne("BookShelf.Core.Models.Book", "Book")
                        .WithMany("BookCategory")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookShelf.Core.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookShelf.Core.Models.BookDetail", b =>
                {
                    b.HasOne("BookShelf.Core.Models.Book", "Book")
                        .WithOne("BookDetail")
                        .HasForeignKey("BookShelf.Core.Models.BookDetail", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookShelf.Core.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookShelf.Core.Models.Book", b =>
                {
                    b.Navigation("BookCategory");

                    b.Navigation("BookDetail");
                });

            modelBuilder.Entity("BookShelf.Core.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
